In [2]:
import json
import numpy as np
import pandas as pd

In [5]:
a = np.array([1., 4., 2., 12.3], dtype=np.float32)

# sum 
print(np.sum(a))
print(a.sum())

# mean
print(np.mean(a))

# std
print(np.std(a))

19.3
19.3
4.825
4.4488063


In [7]:
print(a[:3]) # slicing
print(a[::-1])

[1. 4. 2.]
[12.3  2.   4.   1. ]


In [9]:
b = np.array([3, 5, 8, 1], dtype=np.float32)
print(a)
print(b)
print(a * b)  # element-wise multiplication

# adding
print(a + b)

# division
print(a / b)

[ 1.   4.   2.  12.3]
[3. 5. 8. 1.]
[ 3.  20.  16.  12.3]
[ 4.   9.  10.  13.3]
[ 0.33333334  0.8         0.25       12.3       ]


In [10]:
# 2D matrix
M = np.random.rand(3, 4)  # 3 rows, 4 columns
print(M)

print(M[:3, :2])  # first 3 rows, first 2 columns

[[0.95325261 0.30097776 0.23097138 0.94040378]
 [0.72917825 0.45145845 0.66271847 0.3907832 ]
 [0.94177472 0.18459881 0.472761   0.97099566]]
[[0.95325261 0.30097776]
 [0.72917825 0.45145845]
 [0.94177472 0.18459881]]


In [11]:
a = np.random.rand(4, 2) # 4 rows, 2 columns

print(M @ a) # matrix multiplication
print(np.dot(M, a))

[[1.00476053 1.05461349]
 [1.16609128 1.42226781]
 [1.10792132 1.13438542]]
[[1.00476053 1.05461349]
 [1.16609128 1.42226781]
 [1.10792132 1.13438542]]


In [13]:
# compute the sum of each row
print(np.sum(M, axis=1)) # [3, ]

# compute the sum of each column
print(np.sum(M, axis=0)) # [4, ]

[2.42560552 2.23413837 2.57013019]
[2.62420558 0.93703501 1.36645085 2.30218263]


In [3]:
import json
import pandas as pd

In [6]:
data_dict = [
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  }
]

with open('data.json', 'w') as f:
    json.dump(data_dict, f, indent=2)

In [7]:
# load data from file
with open('data.json', 'r') as f:
    data = json.load(f)

print(data)

[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}]


In [8]:
print(type(data))  # list
print(type(data[0]))  # dict

<class 'list'>
<class 'dict'>


In [9]:
print(data[0]["name"])

Leanne Graham


In [11]:
# convert to DataFrame
df = pd.read_json('data.json')
# print(df)
print(df.columns)

Index(['id', 'name', 'username', 'email', 'address', 'phone', 'website',
       'company'],
      dtype='object')


In [12]:
df2 = pd.DataFrame(data)
print(df2.columns)

Index(['id', 'name', 'username', 'email', 'address', 'phone', 'website',
       'company'],
      dtype='object')


In [14]:
# method 1: convert to dataframe directly, and select columns
df_selected = df2[['id', 'name', 'email', 'address']]
# print(df_selected)
# Need to process the 'address' column to extract the city

for i, row in df_selected.iterrows():
    address = row['address']
    city = address['city']
    df_selected.at[i, 'city'] = city
print(df_selected)

   id           name              email  \
0   1  Leanne Graham  Sincere@april.biz   

                                             address         city  
0  {'street': 'Kulas Light', 'suite': 'Apt. 556',...  Gwenborough  


/var/folders/jv/gl5_9qzs2b3d18bbq7bzqpg40000gn/T/ipykernel_50610/1508439228.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected.at[i, 'city'] = city


In [16]:
# method 2: create new pd.DataFrame and loop through data
df = pd.DataFrame(columns=['id', 'name', 'email', 'city'])
print(df)
for i, item in enumerate(data):
    id_ = item['id']
    name = item['name']
    email = item['email']
    city = item['address']['city']
    df.loc[i] = [id_, name, email, city]
print(df)

Empty DataFrame
Columns: [id, name, email, city]
Index: []
   id           name              email         city
0   1  Leanne Graham  Sincere@april.biz  Gwenborough


In [18]:
# select id == 1 and name == 'Leanne Graham'
print(df[(df['id'] == 1) & (df['name'] == 'Leanne Graham')]) # & is and operator, | is or operator

# select id > 1
print(df[df['id'] > 1])

   id           name              email         city
0   1  Leanne Graham  Sincere@april.biz  Gwenborough
Empty DataFrame
Columns: [id, name, email, city]
Index: []


In [19]:
# save to csv
file_name = 'output.csv'
df.to_csv(file_name, index=False)